app = "donation-page"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
  dockerfile = "Dockerfile"

[env]
  REACT_APP_DONATION_SERVER_URL = "https://donation-server.fly.dev"